#!/bin/sh /etc/rc.common

START=90
STOP=1
USE_PROCD=1
NAME=presence-detector
PROG=/etc/config/presence-detector.sh

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_set_param term_timeout 30
	procd_close_instance
}
